name: tmp
on:
  push:
    branches:
      - '*'

jobs:
  CI:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.2']
    name: CI
    steps:
    - name: Psalm
      run: |
        echo "here"
        composer install -vvv
        echo "there"
        php vendor/bin/psalm
        echo "done"
