name: tmp
on:
  push:
    branches:
      - '*'

jobs:
  CI:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.2']

    name: CI
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Psalm
        run: |
          pwd
          ls -la
          composer install -vvv
          php vendor/bin/psalm
